# Tetorica mDrop configuration file

# Shared file or directory
path = "/opt/homebrew/var/tetorica-mdrop/share"

# Server bind hostname / address
# Examples:
# "mdrop.local" -> Bonjour / mDNS hostname
hostname = "mdrop.local"

# HTTP server port
port = 7878

# Disable Bonjour / mDNS advertisement
no_bonjour = false

# Allow only local network access
local_only = true

# Enable HTTPS mode
# Usually disabled when using nginx reverse proxy
is_https = false

# Optional built-in authentication
# Recommended only for simple local usage
id = ""

password = ""



# Install BREW For Linux

```
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc
```

